import { StyleSheet } from "react-native";
export const allDesignsStyles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: "#f9fafb",
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 16,
      paddingVertical: 12,
      backgroundColor: "transparent",
    },
    headerBackButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: "transparent",
      alignItems: "center",
      justifyContent: "center",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    headerBackText: {
      fontSize: 20,
      color: "#fb7185",
      fontWeight: "bold",
    },
    designsList: {
      paddingHorizontal: 8,
      paddingTop: 16,
      paddingBottom: 20,
    },
    designCard: {
      flex: 1,
      backgroundColor: "#fff",
      borderRadius: 16,
      margin: 8,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 3,
      overflow: "hidden",
    },
    designCardRight: {
      // Additional styling for right column if needed
    },
    designImageContainer: {
      position: "relative",
      height: 180,
    },
    designImage: {
      width: "100%",
      height: "100%",
      backgroundColor: "#f3f4f6",
    },
    rankBadge: {
      position: "absolute",
      top: 12,
      left: 12,
      backgroundColor: "#fb7185",
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 12,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 2,
    },
    rankText: {
      fontSize: 10,
      color: "#fff",
      fontWeight: "700",
    },
    bookmarkButton: {
      position: "absolute",
      top: 12,
      right: 12,
      width: 32,
      height: 32,
      backgroundColor: "rgba(255,255,255,0.9)",
      borderRadius: 16,
      justifyContent: "center",
      alignItems: "center",
    },
    bookmarkIcon: {
      fontSize: 14,
    },
    difficultyBadge: {
      position: "absolute",
      bottom: 12,
      left: 12,
      backgroundColor: "rgba(0,0,0,0.7)",
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 8,
    },
    difficultyText: {
      fontSize: 10,
      color: "#fff",
      fontWeight: "600",
    },
    designInfo: {
      padding: 12,
    },
    designTitle: {
      fontSize: 14,
      fontWeight: "600",
      color: "#111827",
      marginBottom: 4,
      lineHeight: 18,
    },
    designCreator: {
      fontSize: 12,
      color: "#6b7280",
      marginBottom: 8,
    },
    designFooter: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    likesContainer: {
      flexDirection: "row",
      alignItems: "center",
    },
    likesIcon: {
      fontSize: 12,
      marginRight: 4,
    },
    likesCount: {
      fontSize: 12,
      fontWeight: "600",
      color: "#111827",
    },
    tagsScroll: {
      flex: 1,
      marginLeft: 8,
    },
    tagMini: {
      backgroundColor: "#fef3f4",
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 6,
      marginRight: 4,
    },
    tagMiniText: {
      fontSize: 10,
      color: "#dc2626",
      fontWeight: "500",
    },
    loadingContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      padding: 40,
    },
    loadingText: {
      fontSize: 16,
      color: "#6b7280",
      marginTop: 16,
      fontWeight: "500",
    },
  });